// API base URLs
export const API_URLS = {
  AUTH: `auth`,
  USER: `users/me`,
  LEARNER_INFO: `learner-infos`,
  LEARNER_GAMIFICATION_STOCK: `learner-gamification-stocks`,
  LEARNER_GAMIFICATION: `learner-gamifications`,
  LEARNER_PROGRESS: `learner-progresses`,
  LEARNER_STREAKS: `learner-streaks`,
  GAMIFICATION_TX: `gamification-txes`,
  GAMIFICATION_TX_AMOUNTS: `gamification-tx-amounts`,
  LANGUAGES: "languages",
  LEARNING_PURPOSE: "learning-purposes",
  LEARNING_GOALS: "learning-goals",
  SOCIAL_TRAFFIC: "social-traffics",
  LEARNING_JOURNEY_POINTER: "learning-journeys",
  CONTENTS: `contents`,
  LEARNING_JOURNEY_UNITS: "learning-journey-units",
  LEARNING_JOURNEY_LEVELS: "learning-journey-levels",
  LEARNING_JOURNEY_LESSONS: "learning-journey-lessons",
  JOURNEY_MAP_QUESTION_CONTENTS: "journey-map-question-contents",
  QUESTION_CONTENT_OPTIONS: "question-content-options",
  QUESTION_CONTENTS: "question-contents",
  QUESTION_DETAILS: "question-details",
  CONTENT_DETAILS: "content-details",
  CONTENT_DETAILS_BY_LANGUAGES: "content-details-by-languages",
  CONTENT_BY_CLAUSES: "content-by-clauses",
  CONTENT_BY_SYLLABLES: "content-by-syllables",
  EXAMS: "exams",
  LEARNER_JOURNEY: "learner-journeys",
  TERMS_AND_CONDITIONS: "term-and-conditions",
  LEARNING_GUIDES: "learning-guides",
  LEARNING_TIPS: "learning-tips",
  PRIVACY_POLICIES: "privacy-policies",
  COUNTRY: "countries",
  PACKAGE_PLAN_DETAILS: "package-plan-details",
  PACKAGE_PLAN: "package-plans",
  SUBSCRIPTIONS_PLAN: "subscription-plans",
  SUBSCRIPTIONS: "subscriptions",
  TOP_TEN_LEADERBOARD: "learner-gamification-stocks/getInjaz",
  USER_LEADERBOARD_POSITION:
    "learner-gamification-stocks/getUserPositionByInjaz",
  PAYMENTS: "payments",
  UNSBUSCRIBE: "payments/unsubscribe",
  DAILY_QUEST: "daily-quests",
  REGISTERED_USER: "registereds",
  SOCIAL_LOGIN: "social-login",
};

// Authentication API endpoints
export const AUTH_URLS = {
  LOGIN: `${API_URLS.AUTH}/local`,
  REGISTER: `${API_URLS.AUTH}/local/register`,
  FORGOT_PASSWORD: `${API_URLS.AUTH}/forgot-password`,
  RESET_PASSWORD: `${API_URLS.AUTH}/reset-password`,
};
