// Define and export tag types as constants
export const TagTypes = {
    USER: "User",
    LEARNER_INFO: "Learner's Information",
    LANGUAGES: "languages",
    CONTENTS: "Contents",
    LEARNING_JOURNEY_UNITS:"Units",
    LEARNING_JOURNEY_LEVELS:"Levels",
    LEARNING_JOURNEY_LESSONS:"Lessons",
    JOURNEY_MAP_QUESTION_CONTENTS:"Journey Map Question Contents",
    QUESTION_CONTENT_OPTIONS:"Question Content Options",
    QUESTION_CONTENTS:"Question Contents",
    QUESTION_DETAILS:"Question Details",
    CONTENT_DETAILS:"Content Details",
    CONTENT_DETAILS_BY_LANGUAGES:"Content Details By Languages",
    LEARNING_PURPOSE:"Learning Purpose",
    LEARNING_GOALS:"Learning Goals",
    SOCIAL_TRAFFIC: "Social Traffic",
    LEARNING_GAMIFICATION_STOCK:"Learning Gamification Information",
    GAMIFICATION_TX:"Gamification TX",
    GAMIFICATION_TX_AMOUNTS:"Gamification TX Amounts",
    CONTENT_BY_CLAUSES:"Content Clauses",
    CONTENT_BY_SYLLABLES:"Content Syllables",
    LEARNER_GAMIFICATION: `learner-gamifications`,
    LEARNER_PROGRESS: "Learner Progress",
    LEARNER_STREAKS: "Learner Streaks",
    EXAMS: "exams",
    LEARNER_JOURNEY: "learner-journeys",
    New_User: "Are you a new user? Click here to register.",
    Existing_User: "Already have an account?",
    LEARNING_JOURNEY_POINTER: "How proficient you are in Arabic?",
    TERMS_AND_CONDITIONS: "TERMS AND CONDITIONS",
    LEARNING_GUIDES: "LEARNING GUIDES",
    LEARNING_TIPS: "LEARNING TIPS",
    PRIVACY_POLICIES: "PRIVACY POLICIES",
    COUNTRY: "NAME OF COUNTRIES",
    PACKAGE_PLAN: "package plan",
    SUBSCRIPTIONS_PLAN: "subscription plan",
    SUBSCRIPTIONS: "subscription",
    PAYMENTS: "payments",
    UNSUBSCRIBE: "Unsubscribe",
    DAILY_QUEST: "Daily Quests"
    // Add other tag types as needed
  };
  